config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/encryption')
  get 'encryption/download/:id' => 'encryption#download', :as => :download
  resources :encryption

end

app/models/my_encryption.rb
class MyEncryption < ActiveRecord::Base
    def self.isTrue(str1,str2)
        if(str1 == str2)
            return true
        end
        return false    
    end
    def self.isValid(txt)
        txt.each_byte do |i|
            if( !((47 < i and i < 58) || (96 < i and i < 103)) )
                return false
            end
        end
        return true
    end
    
    def self.isValidAES(keys,length)
        if(keys[:key] == "")
            return "Error: You can not leave AES key empty."
        end
        size = keys[:key].size
        if(size != length/4 )
            return "Error: AES key is not " + length.to_s + "bits(" + (length/4).to_s + "chr)"
        end
        if(  (! isValid(keys[:key])) )
            return "Error: invalid key, AES key only contain 0~9 and a~f"
        end
    end
    
    def self.isValidTripleDES(keys)
        if(keys[:key1] == "" or keys[:key2] == "" or keys[:key3] == "")
            return "Error: You can not leave key1 or key2 or key3 empty."
        end
        size1 = keys[:key1].size
        size2 = keys[:key2].size
        size3 = keys[:key3].size
        if(size3 != 14 and size1 != 14 and size2 != 14)
            return "Error: key1 or key2 or key3 is not 56bits(14chr)"
        end
        if(  (! isValid(keys[:key1])) or (! isValid(keys[:key1])) )
            return "Error: invalid key, key1 and key2 only contain 0~9 and a~f"
        end
    end
    
    def self.isEncryptionValid(encryption,keys)
        if(encryption == "TripleDES")
            return isValidTripleDES(keys)
        elsif(encryption == "AES128")
            return isValidAES(keys,128)
        elsif(encryption == "AES192")
            return isValidAES(keys,192)
        elsif(encryption == "AES256")
            return isValidAES(keys,256)
        else
            return "Error: Invalid Encryption method"
        end
        return nil
    end
    def self.isDecryptionValid(decryption,cipher,keys)
        if(!isValid(cipher))
            return "Error: wrong cipher, cipher should only contain 0~9 and a~f"
        end
        return isEncryptionValid(decryption,keys)
    end
    
    def self.getType(encryption)
        if(encryption == "TripleDES")
            return 0
        elsif(encryption == "AES128")
            return 1
        elsif(encryption == "AES192")
            return 2
        elsif(encryption == "AES256")
            return 3
        end
        return 0
    end
    
    def self.runEncryption(encryption,message,keys)
        if(encryption == "TripleDES")
            return TripleDES.encrypt(message,keys[:key1],keys[:key2],keys[:key3])
        elsif(encryption == "AES128")
           return AES.encrypt(message,keys[:key])
        elsif(encryption == "AES192")
            return AES.encrypt(message,keys[:key])
        elsif(encryption == "AES256")
            return AES.encrypt(message,keys[:key])
        end
        return "Error: Programmer should never see this line"
    end
    def self.runDecryption(decryption,cipher,keys)
        if(decryption == "TripleDES")
            return TripleDES.decrypt(cipher,keys[:key1],keys[:key2],keys[:key3])
        elsif(decryption == "AES128")
           return AES.decrypt(cipher,keys[:key])
        elsif(decryption == "AES192")
            return AES.decrypt(cipher,keys[:key])
        elsif(decryption == "AES256")
            return AES.decrypt(cipher,keys[:key])
        end
        return "Error: Programmer should never see this line"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/encryption_controller.rb
require 'AES'
require 'TripleDES'
require 'EncryptionTest'
class EncryptionController < ApplicationController
    def index
    end
    
    # when user submit a request, we do encryption or decryption
    def create
        if(params[:commit] != nil)
            session[:encryption] = params[:encryption]
            session[:message] = params[:message]
            session[:cipher] = params[:cipher]
            keys = params[:keys]
            session[:key] = keys[:key]
            session[:key1] = keys[:key1]
            session[:key2] = keys[:key2]
            session[:key3] = keys[:key3]
        end
        if(params[:commit] == "Encrypt")
            invalid = MyEncryption.isEncryptionValid(params[:encryption],params[:keys])
            if(invalid == nil)
                start = Time.now
                session[:cipher] = MyEncryption.runEncryption(params[:encryption],params[:message],params[:keys])
                finish = Time.now
                flash[:time] = (finish- start).to_s
            else
                flash[:error] = invalid
            end
        elsif (params[:commit] == "Decrypt")
            invalid = MyEncryption.isDecryptionValid(params[:encryption],params[:cipher],params[:keys])
            if(invalid == nil)
                start = Time.now
                session[:message] = MyEncryption.runDecryption(params[:encryption],params[:cipher],params[:keys])
                finish = Time.now
                flash[:time] = (finish- start).to_s
            else
                flash[:error] = invalid
            end
        elsif (params[:commit] == "Auto Test")
            start = Time.now
            session[:message] = EncryptionTest.auto_test(50,MyEncryption.getType(session[:encryption]))
            finish = Time.now
            flash[:time] = (finish- start).to_s
        else
            #flash[:error] = "Invalid request"
        end
        redirect_to encryption_index_path
    end
    def download
        @path = File.join(Rails.root, "lib")
        if(params[:id] == "1")
            send_file( File.join(@path, "EncryptionHeader.rb"),:type => 'text/html; charset=utf-8')
        elsif(params[:id] == "2")
            send_file( File.join(@path, "TripleDES.rb"))
        elsif(params[:id] == "3")
            send_file( File.join(@path, "AES.rb"))
        elsif(params[:id] == "4")
            send_file( File.join(@path, "EncryptionTest.rb"))
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encryption_helper.rb
module EncryptionHelper
end

app/views/encryption/index.html.haml
//- content_for(:title, 'Encryption')
- content_for(:head) do
    %title Encryption
    = stylesheet_link_tag "encryption"
    //= javascript_include_tag 'record_and_play'
%div.warpper1
    %div.warpper2
        %div.encryption_table
            = form_tag "/encryption" do
                %div.table_left
                    %div.left_top
                        %ul.layout_radio_button
                            %ul
                                %li TripleDES:
                                %li.align_right=radio_button_tag :encryption,:TripleDES,MyEncryption.isTrue(session[:encryption],"TripleDES")
                            %ul.align_right
                                %li AES(128bits)
                                %li.align_right=radio_button_tag :encryption,:AES128,MyEncryption.isTrue(session[:encryption],"AES128")
                        %ul.layout_radio_button
                            %ul
                                %li AES(192bits)
                                %li.align_right=radio_button_tag :encryption,:AES192,MyEncryption.isTrue(session[:encryption],"AES192")
                            %ul.align_right
                                %li AES(256bits)
                                %li.align_right=radio_button_tag :encryption,:AES256,MyEncryption.isTrue(session[:encryption],"AES256")
                    %div.left_mid
                        %ul.layout_input_box
                            %li AES Key:
                            %li.align_right= text_field :keys, :key,:value => session[:key]
                        %ul.layout_input_box
                            %li TripleDES key1:
                            %li.align_right= text_field :keys, :key1,:value => session[:key1]
                        %ul.layout_input_box
                            %li TripleDES key2:
                            %li.align_right= text_field :keys, :key2,:value => session[:key2]
                        %ul.layout_input_box
                            %li TripleDES key3:
                            %li.align_right= text_field :keys, :key3,:value => session[:key3]
                    %div.left_bottom
                        %h4 Message:
                        =text_area_tag :message,session[:message],:class => "scroll_bar"
                %div.table_mid
                    %div.mid_top
                        %h1 Encryption Simulator
                        %p.red= flash[:error]
                    %div.mid_mid
                        %ul
                            %li= submit_tag 'Encrypt'
                            %li= submit_tag 'Decrypt'
                            %li= submit_tag 'Auto Test'
                    %div.mid_bottom
                        %ul
                            %h3 Download Links:
                        %ul
                            %li= link_to "Download EncryptionHeader.rb", download_path(1)
                            %li.align_right= link_to "Download TripleDES.rb",download_path(2)
                        %ul
                            %li= link_to "Download AES.rb",download_path(3)
                            %li.align_right= link_to "Download EncryptionTest.rb", download_path(4)
                        %ul
                            %li.hint Auto test=10s. Download file=refresh page again
                %div.table_right
                    %div.right_top 
                        %h4 Time Spend: #{flash[:time]}
                        %p.g_inline Audio Record test:
                        =button_tag "Record&Play", :onclick=> "RecordAndPlay(this);"
                    %div.right_bottom
                        %h4 Enciphered data:
                        =text_area_tag :cipher,session[:cipher],:class => "scroll_bar"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag "application"
    = javascript_include_tag 'application'
    = yield(:head)
  %body
    = yield